build digibyte:
  extends: .generic-build
  variables:
    FULLNODE: digibyte
    VERSION: "8_26_1"

publish digibyte:
  extends: .generic-publish
  variables:
    FULLNODE: digibyte
    VERSION: "8_26_1"
