build op-geth:
  extends: .generic-build
  variables:
    FULLNODE: op-geth
    VERSION: "1_101605_0"

publish op-geth:
  extends: .generic-publish
  variables:
    FULLNODE: op-geth
    VERSION: "1_101605_0"
