build op-geth:
  extends: .generic-build
  variables:
    FULLNODE: op-geth
    VERSION: "1_101603_4"

publish op-geth:
  extends: .generic-publish
  variables:
    FULLNODE: op-geth
    VERSION: "1_101603_4"
