build op-node:
  extends: .generic-build
  variables:
    FULLNODE: op-node
    VERSION: "1_16_5"

publish op-node:
  extends: .generic-publish
  variables:
    FULLNODE: op-node
    VERSION: "1_16_5"
